### PR TITLE
conda activate bugfix

### PR DESCRIPTION
**Pull request by laestrada**
### Name and Institution (Required)

Name: Lucas Estrada
Institution: Harvard ACMG

### Describe the update
Depending on the conda/miniconda/mamba distribution the way we load conda is faulty. It's best to source the bashrc file directly imo. This also makes it compatible with micromamba aliased as conda.

### CODE REVIEW

**Review by msulprizio — APPROVED** [review]
Looks good to merge!

**Comment by lizziel** [comment]
I had to restore the config file to the old way in order to work on a new cluster I am implementing the IMI on. I can make a PR to add the old way as a commented out option if the default way does not work.

**Comment by laestrada** [comment]
Hi @lizziel 

We updated this to source a user-defined `CondaFile` in config.yml with the default set to `~/.bashrc`. I think it would work to make a conda_activate.sh script that looks like this:
```
#!/bin/bash
eval "$(conda shell.bash hook)"
```

and then set `CondaFile: /path/to/conda_activate.sh`

What do you think?

**Comment by lizziel** [comment]
Great idea! I tested this and it works.

**Pull request merged**
